### ISSUE TITLE
Please don't depend on racket 6.5.0.4!

### ISSUE THREAD

**Issue by AlexKnauth** [jackfirth/predicates#1]
This package depends on `"cover"`, which now depends on `("base" #:version "6.5.0.4")`. Is it necessary to depend on `cover` at all? Could the travis builds download it separately so that a normal download doesn't have to deal with this?

This problem was caused by the `cover` package not having a version exception for racket version 6.1.1, which I have also raised an issue for here (https://github.com/florence/cover/issues/127, now fixed). But it seems like this package shouldn't need to depend on `cover` in order to use it in the travis builds.

**Comment by AlexKnauth** [comment]
Like what Alexis King did here:
https://github.com/lexi-lambda/threading/commit/4600f363e220bcf7986730fc030507417dbc7b20

**Comment by jackfirth** [comment]
This was a surprising issue title to read in my notifications.

You're absolutely right, and all of my newer packages don't directly depend on cover. They install it during the Travis build. I'll make that change here when I get a chance, but honestly I don't pay much attention to this package anymore. If you'd like to open a PR, I'd be very grateful.
