### ISSUE TITLE
Make `all?` and `or?` work on n-ary predicates

### ISSUE THREAD

**Issue by eduardoleon** [jackfirth/predicates#3]
The functions `all?` and `or?` only work on unary predicates. Could you generalize them to work on arbitrary predicates? For example:

``` racket
(define list-eq? (all? eq?))
(define foo (list 1 2 3))
(define bar (list 1 2 3))
(list-eq? foo bar) ;; #t
(list-eq? (list foo) (list foo)) ;; #t
(list-eq? (list foo) (list bar)) ;; #f
```

**Comment by jackfirth** [comment]
They could, but I chose to restrict them to unary predicates to make contract checking and documentation more helpful. The library makes an unwritten stance that _predicates_ are single-argument only and _relations_ are "n-ary predicates" with n greater than two, as I've generally found I use predicates and relations for vastly different things.

**Comment by eduardoleon** [comment]
Ah, okay. Sorry, then.
